apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycustomresources.mygroup-b.example.com
spec:
  group: mygroup-b.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer    
  names:
    kind: MyCustomResource
    plural: mycustomresources
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object