apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    pv-name: my-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-storage-class
  hostPath:
    path: C:\work\minikube