apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    pv-name: my-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: C:\work\minikube
    type: DirectoryOrCreate